# Site settings
name: mkchandler.com
url: https://mkchandler.com
permalink: /:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - buildspec.yml
  - Gemfile
  - Gemfile.lock
  - README.md
